//*
// Openapi related messages.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.5.1
// source: api/openapi/v1/openapi.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// error code enum.
type Retcode int32

const (
	Retcode_ok            Retcode = 0
	Retcode_badRequest    Retcode = 400
	Retcode_internalError Retcode = 500
)

// Enum value maps for Retcode.
var (
	Retcode_name = map[int32]string{
		0:   "ok",
		400: "badRequest",
		500: "internalError",
	}
	Retcode_value = map[string]int32{
		"ok":            0,
		"badRequest":    400,
		"internalError": 500,
	}
)

func (x Retcode) Enum() *Retcode {
	p := new(Retcode)
	*p = x
	return p
}

func (x Retcode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Retcode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_openapi_v1_openapi_proto_enumTypes[0].Descriptor()
}

func (Retcode) Type() protoreflect.EnumType {
	return &file_api_openapi_v1_openapi_proto_enumTypes[0]
}

func (x Retcode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Retcode.Descriptor instead.
func (Retcode) EnumDescriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{0}
}

//*
// plugin state enum.
type PluginStatus int32

const (
	PluginStatus_error    PluginStatus = 0
	PluginStatus_starting PluginStatus = 1
	PluginStatus_runing   PluginStatus = 2
	PluginStatus_stopping PluginStatus = 3
	PluginStatus_stopped  PluginStatus = 4
)

// Enum value maps for PluginStatus.
var (
	PluginStatus_name = map[int32]string{
		0: "error",
		1: "starting",
		2: "runing",
		3: "stopping",
		4: "stopped",
	}
	PluginStatus_value = map[string]int32{
		"error":    0,
		"starting": 1,
		"runing":   2,
		"stopping": 3,
		"stopped":  4,
	}
)

func (x PluginStatus) Enum() *PluginStatus {
	p := new(PluginStatus)
	*p = x
	return p
}

func (x PluginStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_openapi_v1_openapi_proto_enumTypes[1].Descriptor()
}

func (PluginStatus) Type() protoreflect.EnumType {
	return &file_api_openapi_v1_openapi_proto_enumTypes[1]
}

func (x PluginStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginStatus.Descriptor instead.
func (PluginStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{1}
}

//*
// message result.
type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret Retcode `protobuf:"varint,1,opt,name=ret,proto3,enum=openapi.v1.Retcode" json:"ret,omitempty"` // response retcode.
	Msg string  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                          // response ret msg.
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_openapi_v1_openapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_openapi_v1_openapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetRet() Retcode {
	if x != nil {
		return x.Ret
	}
	return Retcode_ok
}

func (x *Result) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

//*
// message brief plugin information.
type BriefPluginInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // plugin id.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // plugin verison.
}

func (x *BriefPluginInfo) Reset() {
	*x = BriefPluginInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_openapi_v1_openapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BriefPluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BriefPluginInfo) ProtoMessage() {}

func (x *BriefPluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_openapi_v1_openapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BriefPluginInfo.ProtoReflect.Descriptor instead.
func (*BriefPluginInfo) Descriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{1}
}

func (x *BriefPluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BriefPluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

//*
// message plugin declares extension point.
type AddonsPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // addons point name.
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"` // addons point description.
}

func (x *AddonsPoint) Reset() {
	*x = AddonsPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_openapi_v1_openapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddonsPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddonsPoint) ProtoMessage() {}

func (x *AddonsPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_openapi_v1_openapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddonsPoint.ProtoReflect.Descriptor instead.
func (*AddonsPoint) Descriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{2}
}

func (x *AddonsPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddonsPoint) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

//*
// message plugin declares implemented other plugin extension point.
type ImplementedAddons struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddonsPoint         string `protobuf:"bytes,1,opt,name=addonsPoint,proto3" json:"addonsPoint,omitempty"` //
	ImplementedEndpoint string `protobuf:"bytes,2,opt,name=implementedEndpoint,proto3" json:"implementedEndpoint,omitempty"`
}

func (x *ImplementedAddons) Reset() {
	*x = ImplementedAddons{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_openapi_v1_openapi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImplementedAddons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplementedAddons) ProtoMessage() {}

func (x *ImplementedAddons) ProtoReflect() protoreflect.Message {
	mi := &file_api_openapi_v1_openapi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplementedAddons.ProtoReflect.Descriptor instead.
func (*ImplementedAddons) Descriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{3}
}

func (x *ImplementedAddons) GetAddonsPoint() string {
	if x != nil {
		return x.AddonsPoint
	}
	return ""
}

func (x *ImplementedAddons) GetImplementedEndpoint() string {
	if x != nil {
		return x.ImplementedEndpoint
	}
	return ""
}

//*
// message plugin implemented other plugin.
type ImplementedPlugin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plugin *BriefPluginInfo     `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"` // implemented plugin information.
	Addons []*ImplementedAddons `protobuf:"bytes,2,rep,name=addons,proto3" json:"addons,omitempty"` // implemented addons point list.
}

func (x *ImplementedPlugin) Reset() {
	*x = ImplementedPlugin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_openapi_v1_openapi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImplementedPlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplementedPlugin) ProtoMessage() {}

func (x *ImplementedPlugin) ProtoReflect() protoreflect.Message {
	mi := &file_api_openapi_v1_openapi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplementedPlugin.ProtoReflect.Descriptor instead.
func (*ImplementedPlugin) Descriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{4}
}

func (x *ImplementedPlugin) GetPlugin() *BriefPluginInfo {
	if x != nil {
		return x.Plugin
	}
	return nil
}

func (x *ImplementedPlugin) GetAddons() []*ImplementedAddons {
	if x != nil {
		return x.Addons
	}
	return nil
}

//*
// The response value of the GET /v1/identify,
// used when the plugin registered.
type IdentifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res               *Result              `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`                             // detail result.
	PluginID          string               `protobuf:"bytes,2,opt,name=pluginID,proto3" json:"pluginID,omitempty"`                   // register plugin id.
	Version           string               `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                     // register plugin version
	TkeelVersion      string               `protobuf:"bytes,4,opt,name=tkeelVersion,proto3" json:"tkeelVersion,omitempty"`           // register plugin depend tkeel version.
	AddonsPoint       []*AddonsPoint       `protobuf:"bytes,5,rep,name=addonsPoint,proto3" json:"addonsPoint,omitempty"`             // register plugin declares addons.
	ImplementedPlugin []*ImplementedPlugin `protobuf:"bytes,6,rep,name=implementedPlugin,proto3" json:"implementedPlugin,omitempty"` // register plugin implemented plugin list.
}

func (x *IdentifyResponse) Reset() {
	*x = IdentifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_openapi_v1_openapi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyResponse) ProtoMessage() {}

func (x *IdentifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_openapi_v1_openapi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyResponse.ProtoReflect.Descriptor instead.
func (*IdentifyResponse) Descriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{5}
}

func (x *IdentifyResponse) GetRes() *Result {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *IdentifyResponse) GetPluginID() string {
	if x != nil {
		return x.PluginID
	}
	return ""
}

func (x *IdentifyResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *IdentifyResponse) GetTkeelVersion() string {
	if x != nil {
		return x.TkeelVersion
	}
	return ""
}

func (x *IdentifyResponse) GetAddonsPoint() []*AddonsPoint {
	if x != nil {
		return x.AddonsPoint
	}
	return nil
}

func (x *IdentifyResponse) GetImplementedPlugin() []*ImplementedPlugin {
	if x != nil {
		return x.ImplementedPlugin
	}
	return nil
}

//*
// The request value of the POST /v1/addons/identify,
// used when the plugin in the registration process implements
// the extension point of the registered plugin.
type AddonsIdentifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plugin            *BriefPluginInfo     `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`                       // implemented plugin information.
	ImplementedAddons []*ImplementedAddons `protobuf:"bytes,2,rep,name=implementedAddons,proto3" json:"implementedAddons,omitempty"` // implemented addons.
}

func (x *AddonsIdentifyRequest) Reset() {
	*x = AddonsIdentifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_openapi_v1_openapi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddonsIdentifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddonsIdentifyRequest) ProtoMessage() {}

func (x *AddonsIdentifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_openapi_v1_openapi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddonsIdentifyRequest.ProtoReflect.Descriptor instead.
func (*AddonsIdentifyRequest) Descriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{6}
}

func (x *AddonsIdentifyRequest) GetPlugin() *BriefPluginInfo {
	if x != nil {
		return x.Plugin
	}
	return nil
}

func (x *AddonsIdentifyRequest) GetImplementedAddons() []*ImplementedAddons {
	if x != nil {
		return x.ImplementedAddons
	}
	return nil
}

//*
// The response value of the POST /v1/addons/identify,
// used when the plugin in the registration process implements
// the extension point of the registered plugin.
type AddonsIdentifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res *Result `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"` // detail result.
}

func (x *AddonsIdentifyResponse) Reset() {
	*x = AddonsIdentifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_openapi_v1_openapi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddonsIdentifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddonsIdentifyResponse) ProtoMessage() {}

func (x *AddonsIdentifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_openapi_v1_openapi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddonsIdentifyResponse.ProtoReflect.Descriptor instead.
func (*AddonsIdentifyResponse) Descriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{7}
}

func (x *AddonsIdentifyResponse) GetRes() *Result {
	if x != nil {
		return x.Res
	}
	return nil
}

//*
// The request value of the POST /v1/tenant/bind,
// used when the tenant administrator enables the plugin.
type TenantBindRequst struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantID string `protobuf:"bytes,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"` // unique tenant id.
	Extra    []byte `protobuf:"bytes,2,opt,name=extra,proto3" json:"extra,omitempty"`       // extra data
}

func (x *TenantBindRequst) Reset() {
	*x = TenantBindRequst{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_openapi_v1_openapi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenantBindRequst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantBindRequst) ProtoMessage() {}

func (x *TenantBindRequst) ProtoReflect() protoreflect.Message {
	mi := &file_api_openapi_v1_openapi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantBindRequst.ProtoReflect.Descriptor instead.
func (*TenantBindRequst) Descriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{8}
}

func (x *TenantBindRequst) GetTenantID() string {
	if x != nil {
		return x.TenantID
	}
	return ""
}

func (x *TenantBindRequst) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

//*
// The response value of the POST /v1/tenant/bind,
// used when the tenant administrator enables the plugin.
type TenantBindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res *Result `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"` // detail result
}

func (x *TenantBindResponse) Reset() {
	*x = TenantBindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_openapi_v1_openapi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenantBindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantBindResponse) ProtoMessage() {}

func (x *TenantBindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_openapi_v1_openapi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantBindResponse.ProtoReflect.Descriptor instead.
func (*TenantBindResponse) Descriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{9}
}

func (x *TenantBindResponse) GetRes() *Result {
	if x != nil {
		return x.Res
	}
	return nil
}

//*
// The request value of the POST /v1/tenant/unbind,
// used when the tenant administrator disables the plugin.
type TenantUnbindRequst struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantID string `protobuf:"bytes,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"` // unique tenant id.
	Extra    []byte `protobuf:"bytes,2,opt,name=extra,proto3" json:"extra,omitempty"`       // extra data
}

func (x *TenantUnbindRequst) Reset() {
	*x = TenantUnbindRequst{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_openapi_v1_openapi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenantUnbindRequst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUnbindRequst) ProtoMessage() {}

func (x *TenantUnbindRequst) ProtoReflect() protoreflect.Message {
	mi := &file_api_openapi_v1_openapi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUnbindRequst.ProtoReflect.Descriptor instead.
func (*TenantUnbindRequst) Descriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{10}
}

func (x *TenantUnbindRequst) GetTenantID() string {
	if x != nil {
		return x.TenantID
	}
	return ""
}

func (x *TenantUnbindRequst) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

//*
// The response value of the POST /v1/tenant/unbind,
// used when the tenant administrator disables the plugin.
type TenantUnbindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res *Result `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"` // detail result
}

func (x *TenantUnbindResponse) Reset() {
	*x = TenantUnbindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_openapi_v1_openapi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenantUnbindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUnbindResponse) ProtoMessage() {}

func (x *TenantUnbindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_openapi_v1_openapi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUnbindResponse.ProtoReflect.Descriptor instead.
func (*TenantUnbindResponse) Descriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{11}
}

func (x *TenantUnbindResponse) GetRes() *Result {
	if x != nil {
		return x.Res
	}
	return nil
}

//*
// The request value of the GET /v1/Status.
// used when the tkeel checks the status of plugins regularly.
type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res    *Result      `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`                                     // detail result
	Status PluginStatus `protobuf:"varint,2,opt,name=status,proto3,enum=openapi.v1.PluginStatus" json:"status,omitempty"` // plugin status.
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_openapi_v1_openapi_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_openapi_v1_openapi_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_openapi_v1_openapi_proto_rawDescGZIP(), []int{12}
}

func (x *StatusResponse) GetRes() *Result {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *StatusResponse) GetStatus() PluginStatus {
	if x != nil {
		return x.Status
	}
	return PluginStatus_error
}

var File_api_openapi_v1_openapi_proto protoreflect.FileDescriptor

var file_api_openapi_v1_openapi_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x41, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x25, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x72,
	0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x3b, 0x0a,
	0x0f, 0x62, 0x72, 0x69, 0x65, 0x66, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x35, 0x0a, 0x0b, 0x61, 0x64,
	0x64, 0x6f, 0x6e, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x22, 0x67, 0x0a, 0x11, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64,
	0x41, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x64, 0x64,
	0x6f, 0x6e, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x65, 0x64, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x7f, 0x0a, 0x11, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12,
	0x33, 0x0a, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x72, 0x69,
	0x65, 0x66, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x12, 0x35, 0x0a, 0x06, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64,
	0x6f, 0x6e, 0x73, 0x52, 0x06, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x22, 0x9a, 0x02, 0x0a, 0x10,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x24, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c,
	0x74, 0x6b, 0x65, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x74, 0x6b, 0x65, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x39, 0x0a, 0x0b, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0b,
	0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x4b, 0x0a, 0x11, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x11, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x65, 0x64, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x22, 0x99, 0x01, 0x0a, 0x15, 0x41, 0x64, 0x64,
	0x6f, 0x6e, 0x73, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x62, 0x72, 0x69, 0x65, 0x66, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x4b, 0x0a, 0x11, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64, 0x6f, 0x6e,
	0x73, 0x52, 0x11, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x41, 0x64,
	0x64, 0x6f, 0x6e, 0x73, 0x22, 0x3e, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x03, 0x72, 0x65, 0x73, 0x22, 0x44, 0x0a, 0x10, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x42, 0x69,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x22, 0x3a, 0x0a, 0x12, 0x54, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x24, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x46, 0x0a, 0x12, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x22, 0x3c,
	0x0a, 0x14, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x68, 0x0a, 0x0e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x03, 0x72, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x36, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x06, 0x0a, 0x02, 0x6f, 0x6b, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0a, 0x62, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x90, 0x03, 0x12, 0x12, 0x0a, 0x0d, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0xf4, 0x03, 0x2a, 0x4e,
	0x0a, 0x0c, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x72, 0x75, 0x6e, 0x69, 0x6e,
	0x67, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x10,
	0x03, 0x12, 0x0b, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x10, 0x04, 0x42, 0x1a,
	0x5a, 0x18, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x70, 0x65,
	0x6e, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_openapi_v1_openapi_proto_rawDescOnce sync.Once
	file_api_openapi_v1_openapi_proto_rawDescData = file_api_openapi_v1_openapi_proto_rawDesc
)

func file_api_openapi_v1_openapi_proto_rawDescGZIP() []byte {
	file_api_openapi_v1_openapi_proto_rawDescOnce.Do(func() {
		file_api_openapi_v1_openapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_openapi_v1_openapi_proto_rawDescData)
	})
	return file_api_openapi_v1_openapi_proto_rawDescData
}

var file_api_openapi_v1_openapi_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_openapi_v1_openapi_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_openapi_v1_openapi_proto_goTypes = []interface{}{
	(Retcode)(0),                   // 0: openapi.v1.retcode
	(PluginStatus)(0),              // 1: openapi.v1.pluginStatus
	(*Result)(nil),                 // 2: openapi.v1.result
	(*BriefPluginInfo)(nil),        // 3: openapi.v1.briefPluginInfo
	(*AddonsPoint)(nil),            // 4: openapi.v1.addonsPoint
	(*ImplementedAddons)(nil),      // 5: openapi.v1.implementedAddons
	(*ImplementedPlugin)(nil),      // 6: openapi.v1.implementedPlugin
	(*IdentifyResponse)(nil),       // 7: openapi.v1.IdentifyResponse
	(*AddonsIdentifyRequest)(nil),  // 8: openapi.v1.AddonsIdentifyRequest
	(*AddonsIdentifyResponse)(nil), // 9: openapi.v1.AddonsIdentifyResponse
	(*TenantBindRequst)(nil),       // 10: openapi.v1.TenantBindRequst
	(*TenantBindResponse)(nil),     // 11: openapi.v1.TenantBindResponse
	(*TenantUnbindRequst)(nil),     // 12: openapi.v1.TenantUnbindRequst
	(*TenantUnbindResponse)(nil),   // 13: openapi.v1.TenantUnbindResponse
	(*StatusResponse)(nil),         // 14: openapi.v1.StatusResponse
}
var file_api_openapi_v1_openapi_proto_depIdxs = []int32{
	0,  // 0: openapi.v1.result.ret:type_name -> openapi.v1.retcode
	3,  // 1: openapi.v1.implementedPlugin.plugin:type_name -> openapi.v1.briefPluginInfo
	5,  // 2: openapi.v1.implementedPlugin.addons:type_name -> openapi.v1.implementedAddons
	2,  // 3: openapi.v1.IdentifyResponse.res:type_name -> openapi.v1.result
	4,  // 4: openapi.v1.IdentifyResponse.addonsPoint:type_name -> openapi.v1.addonsPoint
	6,  // 5: openapi.v1.IdentifyResponse.implementedPlugin:type_name -> openapi.v1.implementedPlugin
	3,  // 6: openapi.v1.AddonsIdentifyRequest.plugin:type_name -> openapi.v1.briefPluginInfo
	5,  // 7: openapi.v1.AddonsIdentifyRequest.implementedAddons:type_name -> openapi.v1.implementedAddons
	2,  // 8: openapi.v1.AddonsIdentifyResponse.res:type_name -> openapi.v1.result
	2,  // 9: openapi.v1.TenantBindResponse.res:type_name -> openapi.v1.result
	2,  // 10: openapi.v1.TenantUnbindResponse.res:type_name -> openapi.v1.result
	2,  // 11: openapi.v1.StatusResponse.res:type_name -> openapi.v1.result
	1,  // 12: openapi.v1.StatusResponse.status:type_name -> openapi.v1.pluginStatus
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_openapi_v1_openapi_proto_init() }
func file_api_openapi_v1_openapi_proto_init() {
	if File_api_openapi_v1_openapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_openapi_v1_openapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_openapi_v1_openapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BriefPluginInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_openapi_v1_openapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddonsPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_openapi_v1_openapi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImplementedAddons); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_openapi_v1_openapi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImplementedPlugin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_openapi_v1_openapi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_openapi_v1_openapi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddonsIdentifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_openapi_v1_openapi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddonsIdentifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_openapi_v1_openapi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TenantBindRequst); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_openapi_v1_openapi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TenantBindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_openapi_v1_openapi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TenantUnbindRequst); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_openapi_v1_openapi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TenantUnbindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_openapi_v1_openapi_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_openapi_v1_openapi_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_openapi_v1_openapi_proto_goTypes,
		DependencyIndexes: file_api_openapi_v1_openapi_proto_depIdxs,
		EnumInfos:         file_api_openapi_v1_openapi_proto_enumTypes,
		MessageInfos:      file_api_openapi_v1_openapi_proto_msgTypes,
	}.Build()
	File_api_openapi_v1_openapi_proto = out.File
	file_api_openapi_v1_openapi_proto_rawDesc = nil
	file_api_openapi_v1_openapi_proto_goTypes = nil
	file_api_openapi_v1_openapi_proto_depIdxs = nil
}
