// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OpenapiClient is the client API for Openapi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenapiClient interface {
	// Query identify.
	Identify(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IdentifyResponse, error)
	// Post addons identify.
	AddonsIdentify(ctx context.Context, in *AddonsIdentifyRequest, opts ...grpc.CallOption) (*AddonsIdentifyResponse, error)
	// Post tenant bind.
	TenantBind(ctx context.Context, in *TenantBindRequst, opts ...grpc.CallOption) (*TenantBindResponse, error)
	// Post tenant bind.
	TenantUnbind(ctx context.Context, in *TenantUnbindRequst, opts ...grpc.CallOption) (*TenantUnbindResponse, error)
	// Query status.
	Tatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
}

type openapiClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenapiClient(cc grpc.ClientConnInterface) OpenapiClient {
	return &openapiClient{cc}
}

func (c *openapiClient) Identify(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IdentifyResponse, error) {
	out := new(IdentifyResponse)
	err := c.cc.Invoke(ctx, "/openapi.v1.Openapi/Identify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openapiClient) AddonsIdentify(ctx context.Context, in *AddonsIdentifyRequest, opts ...grpc.CallOption) (*AddonsIdentifyResponse, error) {
	out := new(AddonsIdentifyResponse)
	err := c.cc.Invoke(ctx, "/openapi.v1.Openapi/AddonsIdentify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openapiClient) TenantBind(ctx context.Context, in *TenantBindRequst, opts ...grpc.CallOption) (*TenantBindResponse, error) {
	out := new(TenantBindResponse)
	err := c.cc.Invoke(ctx, "/openapi.v1.Openapi/TenantBind", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openapiClient) TenantUnbind(ctx context.Context, in *TenantUnbindRequst, opts ...grpc.CallOption) (*TenantUnbindResponse, error) {
	out := new(TenantUnbindResponse)
	err := c.cc.Invoke(ctx, "/openapi.v1.Openapi/TenantUnbind", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openapiClient) Tatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/openapi.v1.Openapi/tatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenapiServer is the server API for Openapi service.
// All implementations must embed UnimplementedOpenapiServer
// for forward compatibility
type OpenapiServer interface {
	// Query identify.
	Identify(context.Context, *emptypb.Empty) (*IdentifyResponse, error)
	// Post addons identify.
	AddonsIdentify(context.Context, *AddonsIdentifyRequest) (*AddonsIdentifyResponse, error)
	// Post tenant bind.
	TenantBind(context.Context, *TenantBindRequst) (*TenantBindResponse, error)
	// Post tenant bind.
	TenantUnbind(context.Context, *TenantUnbindRequst) (*TenantUnbindResponse, error)
	// Query status.
	Tatus(context.Context, *emptypb.Empty) (*StatusResponse, error)
	mustEmbedUnimplementedOpenapiServer()
}

// UnimplementedOpenapiServer must be embedded to have forward compatible implementations.
type UnimplementedOpenapiServer struct {
}

func (UnimplementedOpenapiServer) Identify(context.Context, *emptypb.Empty) (*IdentifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Identify not implemented")
}
func (UnimplementedOpenapiServer) AddonsIdentify(context.Context, *AddonsIdentifyRequest) (*AddonsIdentifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddonsIdentify not implemented")
}
func (UnimplementedOpenapiServer) TenantBind(context.Context, *TenantBindRequst) (*TenantBindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantBind not implemented")
}
func (UnimplementedOpenapiServer) TenantUnbind(context.Context, *TenantUnbindRequst) (*TenantUnbindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantUnbind not implemented")
}
func (UnimplementedOpenapiServer) Tatus(context.Context, *emptypb.Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tatus not implemented")
}
func (UnimplementedOpenapiServer) mustEmbedUnimplementedOpenapiServer() {}

// UnsafeOpenapiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenapiServer will
// result in compilation errors.
type UnsafeOpenapiServer interface {
	mustEmbedUnimplementedOpenapiServer()
}

func RegisterOpenapiServer(s grpc.ServiceRegistrar, srv OpenapiServer) {
	s.RegisterService(&Openapi_ServiceDesc, srv)
}

func _Openapi_Identify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenapiServer).Identify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openapi.v1.Openapi/Identify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenapiServer).Identify(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openapi_AddonsIdentify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddonsIdentifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenapiServer).AddonsIdentify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openapi.v1.Openapi/AddonsIdentify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenapiServer).AddonsIdentify(ctx, req.(*AddonsIdentifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openapi_TenantBind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantBindRequst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenapiServer).TenantBind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openapi.v1.Openapi/TenantBind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenapiServer).TenantBind(ctx, req.(*TenantBindRequst))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openapi_TenantUnbind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantUnbindRequst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenapiServer).TenantUnbind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openapi.v1.Openapi/TenantUnbind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenapiServer).TenantUnbind(ctx, req.(*TenantUnbindRequst))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openapi_Tatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenapiServer).Tatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openapi.v1.Openapi/tatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenapiServer).Tatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Openapi_ServiceDesc is the grpc.ServiceDesc for Openapi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Openapi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openapi.v1.Openapi",
	HandlerType: (*OpenapiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Identify",
			Handler:    _Openapi_Identify_Handler,
		},
		{
			MethodName: "AddonsIdentify",
			Handler:    _Openapi_AddonsIdentify_Handler,
		},
		{
			MethodName: "TenantBind",
			Handler:    _Openapi_TenantBind_Handler,
		},
		{
			MethodName: "TenantUnbind",
			Handler:    _Openapi_TenantUnbind_Handler,
		},
		{
			MethodName: "tatus",
			Handler:    _Openapi_Tatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/openapi/v1/server.proto",
}
